__title__ = "prompt_generator"
__version__ = "0.0.3"
__summary__ = "A lightweight prompt generator for Python. Primarily for text to image synthesis."
__uri__ = "https://github.com/Just-Understanding-Data-Ltd/promp_gen"
__author__ = "James Antony Phoenix"
__email__ = "jamesaphoenix@googlemail.com"
__license__ = "MIT"
